security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        users:
            entity:
                class: App\Entity\User
                property: 'email'
        in_memory: { memory: ~ }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: users
            guard:
                authenticators:
                    - App\Security\Authenticator
            logout:
                path: logout

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

            switch_user: true

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password-forgotten, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/externe, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mot-de-passe, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_REMEMBERED }
