parameters:
  permissions:
    Menu paramétrage:
      App\Entity\Role::GENERAL_EXPORT: Export général
      App\Entity\Role::MANAGE_SETTINGS: Modifier le paramétrage global
      App\Entity\Role::MANAGE_USERS: Créer et modifier les utilisateurs
      App\Entity\Role::MANAGE_ROLES: Créer et modifier les rôles
      App\Entity\Role::MANAGE_QUALITIES: Créer et modifier les qualités
      App\Entity\Role::MANAGE_IMPORTS: Créer et modifier les imports

    Menu référentiel:
      App\Entity\Role::MANAGE_CLIENTS: Créer et modifier les clients
      App\Entity\Role::MANAGE_GROUPS: Gérer les groupes
      App\Entity\Role::MANAGE_LOCATIONS: Gestion des emplacements
      App\Entity\Role::MANAGE_BOX_TYPES: Créer et modifier des types de box

    Menu traçabilité:
      App\Entity\Role::MANAGE_BOXES: Créer et modifier des Box
      App\Entity\Role::MANAGE_MOVEMENTS: Créer et modifier des mouvements
      App\Entity\Role::MANAGE_DEPOSIT_TICKETS: Créer et modifier des tickets consigne
      App\Entity\Role::MANAGE_ORDERS: Gestion des commandes


  menu:
    - name: Accueil
      icon: home
      type: link
      route: home
    - name: Traçabilité
      icon: bullseye
      type: category
      items:
        - name: Box
          permission: App\Entity\Role::MANAGE_BOXES
          route: boxes_list
        - name: Suivi ticket-consigne
          permission: App\Entity\Role::MANAGE_DEPOSIT_TICKETS
          route: deposit_tickets_list
        - name: Mouvements
          permission: App\Entity\Role::MANAGE_MOVEMENTS
          route: tracking_movements_list
        - name: Commande
          permission: App\Entity\Role::MANAGE_ORDERS
          route: orders_list
    - name: Référentiel
      icon: address-card
      type: category
      items:
        - name: Client
          route: clients_list
          permission: App\Entity\Role::MANAGE_CLIENTS
        - name: Groupe
          route: groups_list
          permission: App\Entity\Role::MANAGE_GROUPS
        - name: Emplacement
          route: locations_list
          permission: App\Entity\Role::MANAGE_LOCATIONS
        - name: Type de box
          route: box_types_list
          permission: App\Entity\Role::MANAGE_BOX_TYPES
    - name: Paramétrage
      icon: cog
      type: category
      items:
        - name: Global
          route: settings
          permission: App\Entity\Role::MANAGE_SETTINGS
        - name: Rôles
          route: roles_list
          permission: App\Entity\Role::MANAGE_ROLES
        - name: Utilisateurs
          route: users_list
          permission: App\Entity\Role::MANAGE_USERS
        - name: Qualités
          route: qualities_list
          permission: App\Entity\Role::MANAGE_QUALITIES
        - name: Imports et mises à jour
          route: imports_list
          permission: App\Entity\Role::MANAGE_IMPORTS
    - name: Déconnexion
      icon: sign-out-alt
      type: link
      route: logout
