parameters:
  web_version: '0.2.0'

  permissions:
    Menu Paramétrage:
      App\Entity\Role::MANAGE_USERS: Créer, modifier, supprimer les utilisateurs
      App\Entity\Role::MANAGE_ROLES: Créer, modifier les rôles
      App\Entity\Role::MANAGE_IMPORTS: Accès à l'import des données

    Menu Traçabilité:
      App\Entity\Role::MANAGE_BOXES: Créer, modifier, supprimer une Box
      App\Entity\Role::MANAGE_MOVEMENTS: Créer, modifier, supprimer un mouvement
      App\Entity\Role::MANAGE_ORDERS: Accès aux scans Box
      App\Entity\Role::MANAGE_DEPOSIT_TICKETS: Créer, supprimer un ticket‑consigne

    Menu Référentiel:
      App\Entity\Role::MANAGE_CLIENTS: Créer, modifier, supprimer les clients
      App\Entity\Role::MANAGE_GROUPS: Créer, modifier les groupes
      App\Entity\Role::MANAGE_LOCATIONS: Créer, modifier, supprimer les emplacements
      App\Entity\Role::MANAGE_BOX_TYPES: Créer, modifier les types de Box

    Autre:
      App\Entity\Role::MANAGE_SETTINGS: Paramétrage global
      App\Entity\Role::GENERAL_EXPORT: Export général
      App\Entity\Role::MANAGE_QUALITIES: Créer, modifier les qualités


  menu:
    - name: Accueil
      icon: home
      type: link
      route: home
    - name: Traçabilité
      icon: bullseye
      type: category
      items:
        - name: Box
          permission: App\Entity\Role::MANAGE_BOXES
          route: boxes_list
        - name: Suivi ticket‑consigne
          permission: App\Entity\Role::MANAGE_DEPOSIT_TICKETS
          route: deposit_tickets_list
        - name: Mouvements
          permission: App\Entity\Role::MANAGE_MOVEMENTS
          route: tracking_movements_list
        - name: Commandes
          permission: App\Entity\Role::MANAGE_ORDERS
          route: orders_list
    - name: Référentiel
      icon: address-card
      type: category
      items:
        - name: Client
          route: clients_list
          permission: App\Entity\Role::MANAGE_CLIENTS
        - name: Groupe
          route: groups_list
          permission: App\Entity\Role::MANAGE_GROUPS
        - name: Emplacement
          route: locations_list
          permission: App\Entity\Role::MANAGE_LOCATIONS
        - name: Type de Box
          route: box_types_list
          permission: App\Entity\Role::MANAGE_BOX_TYPES
    - name: Paramétrage
      icon: cog
      type: category
      items:
        - name: Global
          route: settings
          permission: App\Entity\Role::MANAGE_SETTINGS
        - name: Rôles
          route: roles_list
          permission: App\Entity\Role::MANAGE_ROLES
        - name: Utilisateurs
          route: users_list
          permission: App\Entity\Role::MANAGE_USERS
        - name: Qualités
          route: qualities_list
          permission: App\Entity\Role::MANAGE_QUALITIES
        - name: Imports et mises à jour
          route: imports_list
          permission: App\Entity\Role::MANAGE_IMPORTS
    - name: Déconnexion
      icon: sign-out-alt
      type: link
      route: logout
