parameters:
  permissions:
    Menu paramétrage:
      App\Entity\Role::GENERAL_EXPORT: Export général
      App\Entity\Role::MANAGE_SETTINGS: Créer et modifier le paramétrage
      App\Entity\Role::MANAGE_USERS: Créer et modifier les utilisateurs
      App\Entity\Role::MANAGE_ROLES: Créer et modifier les rôles
      App\Entity\Role::MANAGE_GROUPS: Créer et modifier les groupes
      App\Entity\Role::MANAGE_CLIENTS: Créer et modifier les clients

    Menu référentiel:
      App\Entity\Role::MANAGE_CLIENT: Créer et modifier un client #voir avec laure si on le garde
      App\Entity\Role::DEACTIVATE_CLIENT: Désactivation client
      App\Entity\Role::DELETE_CLIENT: Suppression client
      App\Entity\Role::MANAGE_GROUPS: Gérer les groupes
      App\Entity\Role::MANAGE_LOCATIONS: Gestion des emplacements

    Menu traçabilité:
      App\Entity\Role::CREATE_BOX: Création Box
      App\Entity\Role::EDIT_BOX: Modification Box
      App\Entity\Role::DEACTIVATE_BOX: Désactivation Box
      App\Entity\Role::IMPORT_BOX: Import de Box
      App\Entity\Role::EXPORT_BOX: Export de Box
      App\Entity\Role::CHECKOUT: Passage en caisse
      App\Entity\Role::DELETE_MOVEMENT: Suppression de mouvement

  menu:
    - name: Accueil
      icon: home
      type: link
      route: home
    - name: Traçabilité
      icon: bullseye
      type: category
      items:
        - name: Box
          route: missing_route
        - name: Numéro consigne
          route: missing_route
        - name: Mouvements
          route: missing_route
    - name: Référentiel
      icon: address-card
      type: category
      items:
        - name: Client
          route: clients_list
        - name: Groupe
          route: groups_list
        - name: Emplacement
          route: locations_list
    - name: Paramétrage
      icon: cog
      type: category
      items:
        - name: Global
          route: settings
        - name: Rôles
          route: roles_list
        - name: Utilisateurs
          route: users_list
        - name: Imports et mises à jour
          route: missing_route
    - name: Déconnexion
      icon: sign-out-alt
      type: link
      route: logout
